version: '3'
services:
  angular-ui:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: angular-ui
    volumes:
      - ./app:/usr/src/app
      - /usr/src/node_modules
